[dependencies]
sqlx = {version = "0.8.3", features = ["sqlite", "runtime-tokio"]}
tokio = {version = "1.20.0", features = ["macros", "rt-multi-thread"]}

[package]
name = "linked"
version = "0.1.0"
edition = "2021"
