# All paths are relative to path from which the binary is ran
# ~ is expanded to $HOME

host = "0.0.0.0"
port = 5005
log_level = "info" # "off" | "error" | "warn" | "info" | "debug" | "trace"
htpasswd_file = "./test-var/htpasswd_example"
db_url = "./test-var/linked.db"
